Repository wordpress-mobile/WordPress-MediaPicker-Android, pull requests merged in 2024-07, with the labels that each got.

#76 [Buildkite] Add Agent Attribute with Queue Android to Every YML File
  .buildkite/pipeline.yml
Labels: Tooling

#77 [Build] Update Kotlin to 1.9.22
  settings.gradle
Labels: Tooling, Core

#78 [Dependency Analysis] Add Android Gradle Plugin
  .buildkite/schedules/dependency-analysis.yml
  build.gradle
  gradle.properties
  settings.gradle
Labels: Tooling, Core

#79 [Build] Update Kotlin to 1.9.24
  settings.gradle
Labels: Tooling, Core

#80 [Dependency Update] Update `a8c-ci-toolkit` to 3.4.2
  .buildkite/pipeline.yml
  .buildkite/schedules/dependency-analysis.yml
  .buildkite/shared-pipeline-vars
Labels: Tooling

#82 Remove not-needed permissions for the Camera function
  mediapicker/src/main/java/org/wordpress/android/mediapicker/util/MediaPickerPermissionUtils.kt
Labels: bug
